version: '3'

services:
    wordpress:
        image: wordpress
        ports:
            - 8080:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8000:80
        environment:
            PMA_HOST: db
            MYSQL_USER: exampleuser
            MYSQL_ROOT_PASSWORD: example


    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_ROOT_PASSWORD: example
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
